version: '3.8'

services:
  web:
    container_name: web
    build: ./src
    command: uvicorn core.main:app --host 0.0.0.0
    volumes:
      - ./src:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - src/.env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432:5432
    environment:
      - POSTGRES_USER=fastapi_traefik
      - POSTGRES_PASSWORD=fastapi_traefik
      - POSTGRES_DB=fastapi_traefik

volumes:
  postgres_data: