"""table Task added is_done column and ondelete CASCADE

Revision ID: 0f34819ce4d8
Revises: 4910564ad11f
Create Date: 2023-07-27 12:20:25.631870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f34819ce4d8'
down_revision = '4910564ad11f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_done', sa.Boolean(), nullable=True))
    op.execute("UPDATE task SET is_done = false")
    op.alter_column('task', 'is_done', nullable=False)
    op.drop_constraint('task_project_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_project_id_fkey', 'task', 'project', ['project_id'], ['id'])
    op.drop_column('task', 'is_done')
    # ### end Alembic commands ###
